// One-off generator for src/widgets/map/country-codes.ts.
//
// Reads the `world-countries` dataset (ISO 3166-1) and emits a compact,
// committed table mapping each country's numeric code (ccn3, matching the
// feature ids in `world-atlas/countries-110m.json`) to its alpha-2 / alpha-3
// codes and common name. The map widget bundles only the generated file, not
// `world-countries` (a devDependency used solely here).
//
// Regenerate:  npx tsx scripts/generate-country-codes.ts

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import worldCountries from "world-countries" assert { type: "json" };

interface RawCountry {
  ccn3: string;
  cca2: string;
  cca3: string;
  name: { common: string };
}

const raw = ((worldCountries as unknown as { default?: RawCountry[] }).default ??
  (worldCountries as unknown as RawCountry[])) as RawCountry[];

const rows = raw
  .filter((c) => c.ccn3 && c.cca3)
  .map((c) => ({ ccn3: c.ccn3, a2: c.cca2, a3: c.cca3, name: c.name.common }))
  .sort((a, b) => a.a3.localeCompare(b.a3));

const body = rows
  .map(
    (r) =>
      `  { ccn3: ${JSON.stringify(r.ccn3)}, a2: ${JSON.stringify(r.a2)}, a3: ${JSON.stringify(
        r.a3,
      )}, name: ${JSON.stringify(r.name)} },`,
  )
  .join("\n");

const out = `// AUTO-GENERATED by scripts/generate-country-codes.ts — do not edit by hand.
// Source: world-countries (ISO 3166-1). Regenerate with:
//   npx tsx scripts/generate-country-codes.ts
//
// \`ccn3\` matches the numeric feature ids in world-atlas/countries-110m.json,
// so the map widget resolves a datum's id (alpha-3 / alpha-2 / numeric / name)
// to a country here, then to the atlas feature by ccn3.

export interface CountryCode {
  /** ISO 3166-1 numeric (matches world-atlas feature ids). */
  ccn3: string;
  /** ISO 3166-1 alpha-2. */
  a2: string;
  /** ISO 3166-1 alpha-3. */
  a3: string;
  /** Common English name. */
  name: string;
}

export const COUNTRY_CODES: readonly CountryCode[] = [
${body}
];
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "src", "widgets", "map", "country-codes.ts");
writeFileSync(target, out);
console.log(`Wrote ${rows.length} countries to ${target}`);
